<?php

$redirectPageData = array(
    1   => array('newUri' => '/odsek/'),
    3   => array('newUri' => '/odsek/vodstvo/'),
    5   => array('newUri' => '/odsek/zgodovina/'),
    6   => array('newUri' => '/pomembnejsi-vzponi/'),
    7   => array('newUri' => '/kontakt/'),
    14  => array('newUri' => '/sola-sportnega-plezanja/'),
    17  => array('newUri' => '/plezalisce-preddvor/'),
    19  => array('newUri' => '/pravno-obvestilo/'),
    27  => array('newUri' => '/odsek/clani/'),
    76  => array('newUri' => '/odsek/pomembni-dokumenti/'),
    89  => array('newUri' => '/odsek/knjiznica/'),
    182 => array('newUri' => '/zahodna-liga/'),
    263 => array('newUri' => '/zahodna-liga/'),
    264 => array('newUri' => '/zahodna-liga/'),
    360 => array('newUri' => '/zahodna-liga/'),
    442 => array('newUri' => '/zahodna-liga/'),
    482 => array('newUri' => '/alpinisticna-sola/'),
    534 => array('newUri' => '/sportno-plezanje-za-otroke/'),
    514 => array('newUri' => '/zahodna-liga/'),
    561 => array('newUri' => '/zahodna-liga/'),
    644 => array('newUri' => '/zahodna-liga/'),
    684 => array('newUri' => '/alpinisticna-sola/'),
    724 => array('newUri' => '/zahodna-liga/'),
    788 => array('newUri' => '/umetne-stene-urnik/'),
    820 => array('newUri' => '/zahodna-liga/'),
    911 => array('newUri' => '/zahodna-liga/'),
);
