---
-   name:   "AO Kranj :: deploy :: code from git"

    git:        repo=git@git.teon.si:aokranj/website
                dest=/home/ao/www/www.aokranj.com
                recursive=no

# Use this when applying to new host, and do not commit it being set to true
#                accept_hostkey=true
