#!/bin/bash



### Common script initialization
#
MYDIR_REL=`dirname $0`
. "$MYDIR_REL/_script-init.sh"



### Run ansible
#
cd $ANSIBLEDIR
ansible-playbook -i hosts playbooks/deploy-to-production.yml
