#!/bin/bash



### Common script initialization
#
MYDIR_REL=`dirname $0`
. "$MYDIR_REL/_script-init.sh"



### Configuration and data gathering
#
DEPLOYLOG=$LOGDIR/deploy.log
GIT_COMMIT_ID=`git rev-parse HEAD`



### Log deploy start
#
CURDATETIME=`date '+%F %T'`
LOGPREFIX="$CURDATETIME $GIT_COMMIT_ID"
echo "$LOGPREFIX: Starting deployment..."



### Set directory permissions
#
chmod 777 $LOGDIR
chmod 777 $TMPDIR



### Run whatever tasks need to be run to deploy
#
echo "$LOGPREFIX: Deployment complete."
