<?php

// Generated by `wp confmaps generate --from-db --values-from-db` on 2022-01-15T13:41:07+00:00.

return [
  'metadata' => [
    'version' => 1,
  ],
  'data' => [
    'admin_email' => 'MUST-OVERRIDE-IN-conf/maps/local.php@UNDEFINED.com',
    'blogname' => 'DEV AO Kranj DEV',
    'home' => 'http://docker.dev.aokranj.com',
    'siteurl' => 'http://docker.dev.aokranj.com',
    'widget_pis_posts_in_sidebar' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'undef-key-action-dump' => 'ignore',
      'value' => [
        3 => [
          'type' => 'array',
          'undef-key-action-dump' => 'ignore',
          'value' => [
            'image_link' => 'http://docker.dev.aokranj.com/aktualno/',
          ],
        ],
      ],
    ],
  ],
];
