<?php

// Generated by `wp configmaps generate --from-db --values-from-db` on 2022-01-15T13:41:07+00:00.

return [
  'metadata' => [
    'version' => 1,
  ],
  'data' => [
    'home' => 'https://stg.aokranj.com',
    'siteurl' => 'https://stg.aokranj.com',
    'widget_pis_posts_in_sidebar' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        3 => [
          'type' => 'array',
          'value' => [
            'image_link' => 'https://stg.aokranj.com/zahodna-liga/',
          ],
        ],
      ],
    ],
  ],
];
