name: Deploy STG



on:
    workflow_dispatch:

    pull_request:
        types: 
            - closed
        branches:
            - master

    push:
        branches:
            - master



jobs:

    deploy:
        name: Deploy to stg.aokranj.com

        # Only run this job in the main repository, and not in any of the forks.
        if: "github.repository == 'aokranj/website-aokranj.com'"

        runs-on: ubuntu-latest
        steps:
            -   name: SSH to stg.aokranj.com and deploy the latest code there
                uses: appleboy/ssh-action@master
                with:
                    host: stg.aokranj.com
                    username: ao-stg
                    key: ${{ secrets.SSH_PRIVKEY_GITHUB_TO_AO_STG }}
                    script_stop: true
                    script: |
                        cd www/stg.aokranj.com
                        git pull
                        ./sbin/deploy-here
